name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Debug Python environment
        run: |
          python -m pip list  # Log installed packages
          python -c "import google.protobuf; print(google.__path__)" || echo "google.protobuf not found"
          python -c "import grpc; print(grpc.__version__)" || echo "grpc not found"

      - name: Generate Proto files
        run: |
          python -m grpc_tools.protoc \
            --proto_path=proto \
            --python_out=src/fileservice \
            --grpc_python_out=src/fileservice \
            proto/file_service.proto

      - name: Check package directory structure
        run: find /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ -name "google"

      - name: Build package
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            FileService.pkg
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: FileService
          path: FileService.pkg