name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest py2app

      - name: Generate Proto files
        run: |
          python -m grpc_tools.protoc \
            --proto_path=proto \
            --python_out=src/fileservice \
            --grpc_python_out=src/fileservice \
            proto/file_service.proto

      - name: Run tests
        run: |
          pip install -e .
          pytest tests/test_file_transfer.py tests/test_service.py -v

      - name: Build package
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            FileService.pkg
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: FileService
          path: FileService.pkg