name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Generate Proto files
        run: |
          python -m grpc_tools.protoc \
            --proto_path=proto \
            --python_out=src/fileservice \
            --grpc_python_out=src/fileservice \
            proto/file_service.proto

      - name: Run tests
        run: |
          pytest tests/ -v